language: node_js
node_js:
  - "11"
cache:
   directories:
     - node_modules
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.2
before_install:
  - openssl aes-256-cbc -K $encrypted_61ddf7a0319b_key -iv $encrypted_61ddf7a0319b_iv
    -in .env.enc -out .env -d
install: 
  - npm install
before_script: 
  - docker-compose -f docker-test.yml up
deploy:  
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
after_script:
  - docker-compose kill
