language: node_js
addons:
  ssh_known_hosts: $DEPLOY_HOST
node_js:
- '11'
cache:
  directories:
  - node_modules
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_61ddf7a0319b_key -iv $encrypted_61ddf7a0319b_iv
  -in .env.enc -out .env -d
install:
- npm install
before_script:
- docker-compose -f docker-test.yml up
before_deploy:
- openssl aes-256-cbc -K $encrypted_61ddf7a0319b_key -iv $encrypted_61ddf7a0319b_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
after_script:
- docker-compose kill
env:
  global:
    secure: Q0MQihhZ774aAFA+iPfz8AYWuMBAWYOwhT2LvxU0RJvSxD+YVkjMD3kXC7ATn4YcHKZgnpi1jtN90LdW18egTI94E/QR2BMMyT5UxAKLWz9TdLryvdJBJ4hewxTasGNRpLTOiPNNrkHvEIft53VwdTfavgMEhlIMln3VChNVMDTnmEiHdI5wQZaU463NdfsYrAyDN9Z+Ak1waqkrbcP80wBfupxQOTPlZHyE66Q4Dqoa3gY/49PLhkvUKpj3Pt+1Ivtyg+qqGODNvH2cI/5e1Hsn9RgRxf1QIOMuqEw57B+Q/vV+ZmWotzZ9KYq6udYSwIlXIuKCdmZeDfOZ5Rg/p5mdCIVPYA9y0JO8Qrpy3Jcwd28tsBzOFPZpy3LWwiqGJCdFq7aA0rjzimNXwSzZX6ct+4hETkVN7tB64BksyXZHJcLsK2YsrMkwVZQdekfxuawqRQS3wNcRmxO8VoZZRoVK5g2i0Edn6lxVAYs7fMb+vYjJAvE32/CcCEGtMPAHxYRyRmcTSWKajGa01LNJCcj9F3UYE2vNODl0I0heBo/5vlWNLuoAanBxURZ5oCxhdJeQ795dvzmssNs14BRVPO4fIvPPo/UUyM6blvzjiB+MW228EbKozZodW9wM8HsdzyXQnDY75MXLCh8lHCsSqMTpTjKM6THGZGu7HvOyaaI=
