language: node_js
addons:
  ssh_known_hosts: "$DEPLOY_HOST"
node_js:
- '11'
cache:
  directories:
  - node_modules
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_61ddf7a0319b_key -iv $encrypted_61ddf7a0319b_iv
  -in secret_files.tar.enc -out secret_files.tar -d
- tar xvf secret_files.tar
install:
- npm install
before_script:
- docker-compose -f docker-test.yml up
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
after_script:
- docker-compose kill