version: "3"

services:
  node:
    build: .
    volumes:
      - ./:/bicibot/backend
      - /bicibot/backend/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm test 
   