version: "3"

services:
  node:
    command: "npx pm2 start src/server.js --no-daemon --interpreter ./node_modules/babel-cli/bin/babel-node.js" # The command docker will execute when starting the container, this command is not allowed to exit, if it does your container will stop
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.bicibot.org"

  reverse-proxy:
    image: traefik:alpine
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /docker/traefik:/etc/traefik
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CLOUDFLARE_EMAIL=${CF_EMAIL}
      - CLOUDFLARE_API_KEY=${CF_API}